{% set name = "elasticsearch-dsl" %}
{% set version = "7.3.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "0ed75f6ff037e36b2397a8e92cae0ddde79b83adc70a154b8946064cb62f7301" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six
    - python-dateutil
    - elasticsearch >=6.0.0,<7.0.0
    - ipaddress  # [py<33]

test:
  imports:
    - elasticsearch_dsl

about:
  home: https://github.com/elasticsearch/elasticsearch-dsl-py
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Higher-level Python client for Elasticsearch
  dev_url: https://github.com/elasticsearch/elasticsearch-dsl-py
  doc_url: https://elasticsearch-dsl.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
