{% set version = "2.1.0" %}

package:
  name: elasticsearch-dsl
  version: {{ version }}

source:
  fn: elasticsearch-dsl-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/elasticsearch-dsl/elasticsearch-dsl-{{ version }}.tar.gz
  sha256: e11881321a2d0f40c78efcc50905f8f6dc090e1929e541727d7abdf5b8a446d9

build:

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - python-dateutil
    - elasticsearch >=2.0.0,<3.0.0

test:
  imports:
    - elasticsearch_dsl

about:
  home: https://github.com/elasticsearch/elasticsearch-dsl-py
  license: Apache 2.0
  summary: 'Higher-level Python client for Elasticsearch'

extra:
  recipe-maintainers:
    - pmlandwehr
