# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "K8mst2fDw+sFmMy37dR866FGk12fokx77XFB7m2S6AuehHPf0LwzzZcZhGey7QxQhbpZa0KHVuckvzVdfYZQxn6tn7IR8IJ+5WWbUHZbo8p6l3Grrp3ON2S6DO1nAY66YE60h4ma/Y8YAcxUfYpsftRrPg5CLWJuyz1Yekd7+5MoggqAnQnoU4del001DquI+PgJEvGoFTRE+Q4Eysq+zzgjR7q8A5S516hDLw8hOrnrPMU1/bQa+doQDAsAVo4ZSMDLWHbU7l4XtSzQH1b9E9bUF3mcuxW12tkRhJWLMeTcjfLX+d2MgQNTYkztrBCj6tK8yyNgyQQV/RrGPo6fPUrdCMhPCxsXmInathvOHZMhOYBf2sMUbEeQk4/1PqYB5wm9uFvnhylHNQnYEOE3JFu6DfgaCOcZk1NGILMJjD17h1je8RoqNXVmzggnSu2pvoM04lGntW7kCvr2uwy7SppMxypFXfPDazwN5xfrVANmSoYZiMtkLAZkg8cLlz1Y69fbd/KtKAdl6FDTlR7H4cEh17A7Xppq6/tLFjs9X4gu7eUBBw+yQhtiu6wKc9+/tSmVwrJ9APBceRBo8KJLs3ioZ2lpjNZbKNpSEhl8Xuj4UL3+imfxuoj5o9SjU1rrw71jvwPioW6f4MVGTuKX5jt/4i+nYZSHIdQfAX03SrQ="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
