travis:
  secure:
    BINSTAR_TOKEN: Oxv98j75NZ8mwB3lVXOkgCFCIONd4ZZ/Hz2iUFx1W0/zk9Do27l0vIPsHgltKJ3l2x9JsCY2wgD4AcMakaxN4TDuuChTzZ6qJO7j0ituDvlPMHSc6g1DEYPyHx3x1x18KGh117OzAoo9XZJVNqg1ppcNxucVRUs/c9STIH3O6+KZtWA/5JV3caUwoiaq3KFquYQSY2I9XZ9jLcmpS5+YcNGkZ3uEjoPIdqJ1PVACCQPa++t4fO//8K9ozYWc4jtnoP2+y8FHy1WTtA8iHflQJgCijYR5qcWol1pxEg9O64yfM5h6fyrqg/j/1s4itSv4PEYCNa4ll0i4Gi2Zkyym4+1LbvfRLfxb+0aOk4ZES+2eKhBcHvC4EeJi0QNCElx7mKPRWe7Bdkrpsajcmf9GDBWNvLSQ2Y8Qwp23Rk1Jqk//K9gy/WLQqONaK9ctRCiVIs7+0MngXNKlphRVVZHaqpydisQo5Y7xl2mJK71Dz/xPtJQzCrrkDEQbt1+ERdB4k/mc/8Az+kRF5r+vJM0uoohnPFMtzqsI5DkieVxFD2kEsR8cAjTkHjAezuq5UDYfC7wmfCz0A99OhESXyOM6N8414Qkwn8dS7JR26d7FOy4ajozNJPEqJL0iWm0K76ENPhAHXnmU007rsYpwAFc6rJqy8ChptigexUnikCeYs9k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
