travis:
  secure:
    BINSTAR_TOKEN: qNd4g2Rq+lcRA5bomgxE+stE5PoRBbEwy1BaMxNNXFG8eH4IVJw/a5lW40A0w7UgIqF/Wo2pj3Anrk+B/wFgaYhjlFtU4pH3Wh6mKVIBby4LI/OZApiu9Ab5cnKwCSk/xDTKgGbNcpWQL+W8CYDURweAP1JV6RUCFdUGX8FvBFCJuq8KUF6ccIDsUqo87Nbv2z0ZPMXV3MS/01nUkH51TrvaoslI71Bel2InHv9f3VxSewvYBCVxivq2JHKodPaJhEE/uXE3jgv70GZlhHN5wObHOPKLz0ZA1I8aQtBcqEMjwI2oJjkJtR+be17Pe8zU05BUsESf7zafik+pemsc3rb6MhHC3/l58tkKcNUXHYmIdI83JBQvX6hbWDE3k+NhiNAef0OFaiyKglADzy0mUiyvKwEZpvrM8SFyXxdzjusjXGppzEW6hmmKu8rNcYNSgTYM5B8loAPs6yB0cWABwbkvgxCjHx7OjzpUJXDm7SN5k+FIDk8YKIo5TbnVRC5api8cgJ/4PQaUFU2LWaeeYGwbkuQFQ1ZQ0aHgMg1vbvwVaw/n6m3pUOjcJMe74o+glt17iTm0Qt6N1b+tAGS2pTZbnWDfCbNqr9FTNLtgqgR75xbjM9dniIyHe5LaWbbTBuIHMniX2cdiyHZSjHRv+pfuLKt30Dn6b1DGA4Wk0bg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
