travis:
  secure:
    BINSTAR_TOKEN: HVWfeTGc28t9qd1tnJLk3fV+UUF8OfImxw+vaQO0A2Vt/HTrL6l1j7YVNBsPZLlJTHcdEpPobZVgjZtgDhPVBpdvhfUdwI0n65kOVA54vMybrukFeaMWXLcp25uBik4YhJOH0RL/3/j7fynIHkY66nSDDzhpo5sTpW/ESqT3oMvUdktBj86QYQ7bR2aiuKNvdl754ZRkxE3GlA/VtmNyEhEjYnZ5odGWBa8oYMbajIz5TeR3aEHhlovoit2zwhBZIeAwPT+Mt5RkKE/ITClb0FA0Jd7DDfI7aUWuX5w0tC7SpBwS320LgoWFUmuK1SahKCsbWjPJSkRFl6WNV0ZVJzdrdbpp3+9a7D4G9iVbi/34948VlYJBAM3p3AajP379reXvTyK8+0lQurEI7NV2wNMbjJlCBOtaY+D0/vfsuRiQ9tlMK1oKV5oqJ3izy8bFyWRW8tt8p6Dp9rEF+oboL7xIFjRu7OFAs4guHrxpS8O+m5wk3RKxorsSQIaKuMQpippFWypM1LQDSrloiPXiP/0rNjFfwbOYPYOw4m7OKyDFjjVaSJDrK6tR/55dlLp7ru4cH+brVxPzDq2BznoKzNN6m/uRKz+WuiPMxxGvV/wtSkc+bqmgWwJ+geyl3OYD5fY0L9P230JzH0S/LdAdOSxMCvXbLBIbYX1isW3DxNc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
