travis:
  secure:
    BINSTAR_TOKEN: vcl/whKYVsQJ18UcG4rMu5TLzqCTE0zDQgv7EvKkv1ya3d/gexCaBuihu72RRlsG3ihMR3SqRnfIW+7k1jDCKCQh99RzBviOt5Q4nrFFhEk14cidA8btapJSnP+Z8DVtO5eYii3yqVcILQzDAghk+s57CnKrevSYz6d0gq9igMiR3s8wSwUul4aC0+3zJnUNVoiVR5it1FrQRLuZyQnOI/+rkabOjLE/Jzq68uQBH/zc/bLskNVI/oSz6YdGElis2PnWWrotktIq73/PsLrih9o5isCoEj/6TFrWOic+r0aChBhyIbfXAUN9TCTnepW7gLe1SZMaHQmNlAR+ib//NliuLJdYXnesdlnOPKWq3QdqUe9javkf2TKoCZVKx6mLoTccFAMyt2Tnir+v3qt6eTRs0iOjGt0WVvkRemIdj48fTCXtpU1Q/L7p535LweA0X5iURfYzOi05lflKYIP5w8Crm4Mxl9dVu91g5wmLhS6hix7LT9PeckbwdoUf/fl8cb46iAV3kSvKdA/oRNGuQD1J8nhmwxmF8h/2ZaiiCz3RHlMwF4daKbolRF8dGDM6WmPfOs7ZciRvKqyMjOcq/ZdPxIbfvcRbOOIk3+HIYjsz3aJ3pECUU3LxBLG97nRz1S4kGsjTSUpEAjunUVYdAZHTXwjtsG5tO+a5sacxUsg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
