travis:
  secure:
    BINSTAR_TOKEN: QcwlFGndXkZ+sv2Zcu6Ok4zOwQXya7lpasHZoxXJbvay7FCAND5oDscb4hYKOFetu4jzzVDVt5J5+NGpPe7NsKcidJQcmXGVG17Rr+hyrsie4En+d3+c1gomwCyfRI/u7x6AtGFydIBFWWJaPXj5I0dvUpjz6l5TRaHvl+SDlCFhYGRDowOi/qOkLUl71LhYE4MXbWIY2Vhg+wwaC30Nvfs2DEhiKznfoQyReEpsgafjyBeOMdSk8+UJk3bJstV2T+4gnDSJLKSNHXtwsOnnlIZQQKpI7AGjDmG2pZbVnNxO3caYhRCJcQqPLAaaKZizm832YfZ1GemjlGKmYuwXRdcWhGbfMI6tzpYEkC0W6vyT2+cfJMFPf3dtNqxSBJU9hnrENsoigW3DgK6Ip5XefLP89gkXHgLUFOdLkzd8DmOafaKN9cIg99xEFBwVGOw7y2O1OHH4RO81tcn7U4taEhtQ4TFYMhhGpGqFFwh6h+fCCZL5Pz2KOCnP8WJrT8hQ+h6jHwBESuBHuTuIV6OHLZa0xon1Nhu8TPU+Z/Zp9L2FuKzawIeQ91FQiXHqDYgHbbvzaA6+jCW1+MaQ7ugX7YW6thqUb4r/yzMhdBMihypZxb0oTr+DyTc61TLKiu4S+yN6IapMetfqxtKjOZZr31HlNHMCPRX1V5mLCD/x3H8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
