travis:
  secure:
    BINSTAR_TOKEN: K8mst2fDw+sFmMy37dR866FGk12fokx77XFB7m2S6AuehHPf0LwzzZcZhGey7QxQhbpZa0KHVuckvzVdfYZQxn6tn7IR8IJ+5WWbUHZbo8p6l3Grrp3ON2S6DO1nAY66YE60h4ma/Y8YAcxUfYpsftRrPg5CLWJuyz1Yekd7+5MoggqAnQnoU4del001DquI+PgJEvGoFTRE+Q4Eysq+zzgjR7q8A5S516hDLw8hOrnrPMU1/bQa+doQDAsAVo4ZSMDLWHbU7l4XtSzQH1b9E9bUF3mcuxW12tkRhJWLMeTcjfLX+d2MgQNTYkztrBCj6tK8yyNgyQQV/RrGPo6fPUrdCMhPCxsXmInathvOHZMhOYBf2sMUbEeQk4/1PqYB5wm9uFvnhylHNQnYEOE3JFu6DfgaCOcZk1NGILMJjD17h1je8RoqNXVmzggnSu2pvoM04lGntW7kCvr2uwy7SppMxypFXfPDazwN5xfrVANmSoYZiMtkLAZkg8cLlz1Y69fbd/KtKAdl6FDTlR7H4cEh17A7Xppq6/tLFjs9X4gu7eUBBw+yQhtiu6wKc9+/tSmVwrJ9APBceRBo8KJLs3ioZ2lpjNZbKNpSEhl8Xuj4UL3+imfxuoj5o9SjU1rrw71jvwPioW6f4MVGTuKX5jt/4i+nYZSHIdQfAX03SrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
