travis:
  secure:
    BINSTAR_TOKEN: wnF4UU6h13SQ5mwRcwWr4AHY0HLINbezLnqrA9kfRQQ0TnQWRxL0/U94q1aEdMYcXwFlf1jfZJtz8qLb5ICKCVt8j9/af/5HxVKe0ZRhhI/gRNPspgpsFxH4kr3K+1Uh3RqPGm2AC/eR0M0EVxSwEXCBeo9cUOdAbgSFJWdhGmssVY1aC2HMWdIX+ICYn6kGBAAT2/lS0uqWq1SqbBPNxLyODw/X4XI9S/G2Y+uEhpQzq+L+UrIMY56N75nnNjaG3LhTarkbvF5dN+52O74y3Wb/KCcYIwAUMvV/k3sxCI+TmXeG5BvZrD5+esz2lPn7N74s8pZ1EpD80veLTmCZjSAwgJoo6d6ayto2PRi0/Eo9PhzdXo0o87HfWRGIB3/x+PFLm4n2gY/j/3phOkRUR7baGK5B9HWoG5ksZef5cMzF3Bk/aa1WDONTYtxQ3GesC0Pk7eRqlwFmbx+/fAj4s4q1qrRHjgbytlUzJFCi0ubG66C+Xu96ZUj4TZj52eLmIb1Il0r4CEjvKjzY63CP7kLa/WOhC0UmFr42X/iGll+8IOGb3nm7L8IYs6wMOkQzQDAsi/KBDs2hF/ow34JaaCU01tAEA+m1bZx4t5Z+69vFMe/K9e+V4cJQYQKoA3vbBpYvqtbMpmpfmi1BvTSPaMJItNSGulgDQi52uhiom2I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
