travis:
  secure:
    BINSTAR_TOKEN: PrQ2XZXMdgmqn+uRQRBfg42YixeJiJ8XqeuiaHl0aBawWtFv2J1ucpakJd5oJYF+4ZcNR4Bb12YJ6Y/gxyeTNyV3K3T9hGzBrR04QCsMY+eemKgvC8/09LlscaQV/2HlrJa0EgIyrG4GFV+q1KsHfY0aU2pRXAaVw6p9m2HNjBvZnMhY+QIwPOINhXbrlKMM2EHpix6pwa15TwgprG0x1LFdpewS3Tij5uBTHVierJJJuICY+Xl37RRoEUQAbGRp3UTAXMXN2xQuUf8aOKRWYclTO85TRQziNtWTmqF0DLGKpcpnMR0qk5X+tBZXI/PvtCwwtZJgJ0yrmR2rRYai8jAbAQXreM4k2ji+srZPWuEVUsyc3ZpYlChNc50jbf8MwkbaDjANbFgno4EbdROLwS2tCLTTSY18zi7FF5Z8T/NHhUlmSQxFQmpKKKHZDDUDCCirnDVGu3ez3SHFJCtJWsMFGVRXRCYl8mswhY7Jv9BvANNz8QrLYDDBMVTDnxHV0t3m/aey1Z02vNmCCV1FI/TZiuMMBAjqfQ12ehJqK5utSOtA2DlAazMdonnTyK3dzSZOQFRr6YMyVlHyEVk127s41KFid57ou7irWQ0PIwIF7rGF9dvgMsM8ycLRrpWzVPuIbPOIxs6+cDK7MMqW1ED4/F36eljzPdxvSieGFcI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
