travis:
  secure:
    BINSTAR_TOKEN: tF99fNPNRBcPvteXesA5CwZZY6ab45+1FWQJIFygQbw0uYSZ8cizmz1jWcgAYJusvY52dIwT1feBSoKaakFL9SOYZszhqYNCsOJeWr5FuSna+xpDPeYOQUElSrxoHFMy67B6d59RFWbYZ3GyhEyeqAz9xzalK7o+kgJR1BSVagNk+x3VPi7zae6wTwkQP8NDrlP/hzDHk5GpQtNOgM9UxqIdwWvlfMnMs+vNjMN2z5xTeswzWa1Kl40p3N7QTE9zDFKuNkY/Mt7zWdUuPZj8PHyMT5vu41VrGVpFpQBCVqJqtFktNh9iKOC+5zUbKsgkjGXD920V2xUuDVKGzhw4m5+06AOPnyn0syt1pc8xTWIa8J6ssm00aBIcI8MBWcZY8bFF9MItlYvOeUbb8fy3rUI/rNrWq8Pb0pmdLmNjDLjDzdEEiqMf7xpnt78fNxZg3PZDv372auRwYVBz8X1MCU9x0fgZ4feLhIdEZDKkIqtkIHdjxWK6F2mCTI++HneET3WyqGdzdti61i2RqPWt2lbDTnKRsVLSliIT6k66lYEUxVIPDFRfgIcov8mLIXcdmKgXkmHfTlmkGHTnQL0BRgCPSV39MD077cMlCFvzMw3dxrpxV7JQFDvoIMBW54jDpjstiMIGJmu+wl0OlyG70krDkh9GYDM7VSF5S7JRwNY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
